package com.api.thecat.typesofcat.enums;

public enum EventsEnum {
    RECEIVED,
    CREATED,
    REQUEST,
    RESPONSE,
    EXCEPTION,
    EXCEPTION_VALIDATION_ERROR,
    EXCEPTION_ARGUMENT_NOT_VALID,
    EXCEPTION_ALREADY_EXISTS,
    EXCEPTION_NOT_FOUND,
    EXCEPTION_UNAUTHORIZED;

}
